# Generated by Django 3.2.5 on 2022-05-13 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0005_remove_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
