# Generated by Django 3.2.5 on 2022-05-13 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
