# Generated by Django 3.2.5 on 2022-05-13 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0008_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
