# Generated by Django 3.2.5 on 2022-05-16 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0013_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
