# Generated by Django 3.2.5 on 2022-05-17 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0024_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
