# Generated by Django 3.2.5 on 2022-05-17 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0030_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
