# Generated by Django 3.2.5 on 2022-05-18 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0039_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
