# Generated by Django 3.2.5 on 2022-05-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0040_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                                      to='ecommerce_app.product')),
            ],
        ),
    ]
