# Generated by Django 3.2.5 on 2022-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0043_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField()),
            ],
        ),
        migrations.RemoveField(
            model_name='map',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(),
        ),
    ]
