# Generated by Django 3.2.5 on 2022-05-18 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0044_auto_20220518_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_id',
        ),
    ]
