# Generated by Django 3.2.5 on 2022-05-18 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0047_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
