# Generated by Django 3.2.5 on 2022-05-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0049_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField()),
            ],
        ),
    ]
