# Generated by Django 3.2.5 on 2022-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0059_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
