# Generated by Django 3.2.5 on 2022-05-19 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0060_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
