# Generated by Django 3.2.5 on 2022-05-19 06:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0063_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
