# Generated by Django 3.2.5 on 2022-05-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0065_alter_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                         to='ecommerce_app.order', unique=True)),
                ('email', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='ecommerce_app.customer')),
            ],
        ),
    ]
