# Generated by Django 3.2.5 on 2022-05-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0067_auto_20220519_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
