# Generated by Django 3.2.5 on 2022-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0068_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
