# Generated by Django 3.2.5 on 2022-06-03 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce_app', '0072_order_orderitem_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
